apiVersion: v2
name: f5-monitoring
version: 2.0.0
description: A collections of tools and dashboards to monitor F5 BIG-IP and NGINX
type: application
keywords:
  - f5
  - bigip
  - nginx
  - ingress
  - waf
  - plus
  - oss
  - grafana
  - prometheus
  - logstash
  - elasticsearch
  - kibana
home: https://www.github.com/rafaelsampaio/f5-monitoring
dependencies:
  - name: prometheus
    version: 18.1.1
    repository: https://prometheus-community.github.io/helm-charts
  - name: grafana
    version: 6.44.10
    repository: https://grafana.github.io/helm-charts
  - name: eck-operator
    version: 2.5.0
    repository: https://helm.elastic.co
maintainers:
  - name: Rafael Sampaio
    email: rafael.sampaio@live.com
    url: https://github.com/rafaelsampaio
appVersion: "1.0.0"