{
 "title": "BIG-IP Traffic",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "BIG-IP",
    "query": {
     "query": "label_values(f5_system_tmmCpu, instance)"
    }
   },
   {
    "name": "vs",
    "label": "VS",
    "query": {
     "query": "label_values(f5_totRequests{instance=~\"$device\"}, virtualServers)"
    }
   },
   {
    "name": "pool",
    "label": "Pool",
    "query": {
     "query": "label_values(f5_totRequests{instance=~\"$device\"}, pools)"
    }
   },
   {
    "name": "member",
    "label": "Member",
    "query": {
     "query": "label_values(f5_totRequests{instance=~\"$device\", pools=~\"$pool\"}, members)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(f5_system_throughputPerformance_inBits_average)",
     "legendFormat": "in"
    },
    {
     "expr": "sum(f5_system_throughputPerformance_outBits_average)",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(f5_system_throughputPerformance_inPackets_average)",
     "legendFormat": "In"
    },
    {
     "expr": "sum(f5_system_throughputPerformance_outPackets_average)",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "TLS TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "t/s" } },
   "targets": [
    {
     "expr": "sum(f5_system_throughputPerformance_sslTps_average)",
     "legendFormat": "tps"
    }
   ]
  },
  {
   "title": "Compression",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum(f5_system_throughputPerformance_compression_average)",
     "legendFormat": "bps avg"
    }
   ]
  },
  { "title": "Device", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "TMM CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(f5_system_tmmCpu{instance=~\"$device\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TMM CPU",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_system_tmmCpu{instance=~\"$device\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TMM Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(f5_system_tmmMemory{instance=~\"$device\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TMM Memory",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_system_tmmMemory{instance=~\"$device\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TMM Client side",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(f5_system_tmmTraffic_clientSideTraffic_bitsIn{instance=~\"$device\"}[$__rate_interval]))",
     "legendFormat": "in"
    },
    {
     "expr": "sum by(instance) (rate(f5_system_tmmTraffic_clientSideTraffic_bitsOut{instance=~\"$device\"}[$__rate_interval]))",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "TMM Server side",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(f5_system_tmmTraffic_serverSideTraffic_bitsIn{instance=~\"$device\"}[$__rate_interval]))",
     "legendFormat": "in"
    },
    {
     "expr": "sum by(instance) (rate(f5_system_tmmTraffic_serverSideTraffic_bitsOut{instance=~\"$device\"}[$__rate_interval]))",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Service traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "f5_system_throughputPerformance_serviceBits_average{instance=~\"$device\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Service pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "f5_system_throughputPerformance_servicePackets_average{instance=~\"$device\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Client connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f5_system_connectionsPerformance_clientConnects_average{instance=~\"$device\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "f5_system_connectionsPerformance_httpRequests_average{instance=~\"$device\"}",
     "legendFormat": " {{instance}}"
    }
   ]
  },
  {
   "title": "Client Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (f5_system_throughputPerformance_clientBitsIn_average{instance=~\"$device\"})",
     "legendFormat": "in"
    },
    {
     "expr": "sum by(instance) (f5_system_throughputPerformance_clientBitsOut_average{instance=~\"$device\"})",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Server Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (f5_system_throughputPerformance_serverBitsIn_average{instance=~\"$device\"})",
     "legendFormat": "in"
    },
    {
     "expr": "sum by(instance) (f5_system_throughputPerformance_serverBitsOut_average{instance=~\"$device\"})",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Compression",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "f5_system_throughputPerformance_compression_average{instance=~\"$device\"}",
     "legendFormat": " {{instance}}"
    }
   ]
  },
  {
   "title": "Management",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by(instance) (f5_system_throughputPerformance_managementBitsIn_average{instance=~\"$device\"})",
     "legendFormat": "in"
    },
    {
     "expr": "sum by(instance) (f5_system_throughputPerformance_managementBitsOut_average{instance=~\"$device\"})",
     "legendFormat": "out"
    }
   ]
  },
  {
   "title": "Server connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f5_system_connectionsPerformance_serverConnections_average{instance=~\"$device\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Server new connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "f5_system_connectionsPerformance_serverNewConnections_average{instance=~\"$device\"}",
     "legendFormat": " {{instance}}"
    }
   ]
  },
  { "title": "Virtual Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 19, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(f5_isEnabled{instance=~\"$device\"}) / count(f5_isEnabled{instance=~\"$device\"})",
     "legendFormat": "Enabled"
    },
    {
     "expr": "sum(f5_isAvailable{instance=~\"$device\"}) / count(f5_isEnabled{instance=~\"$device\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(f5_activeMemberCnt{pools=~\"$pool\", instance=~\"$device\"})",
     "legendFormat": "Active pool members"
    }
   ]
  },
  {
   "title": "Traffic In",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(f5_clientside_bitsIn{instance=~\"$device\", virtualServers=~\"$vs\"}[$__rate_interval])",
     "legendFormat": "{{virtualServers}}"
    }
   ]
  },
  {
   "title": "Traffic Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(f5_clientside_bitsOut{instance=~\"$device\", virtualServers=~\"$vs\"}[5m])",
     "legendFormat": "{{virtualServers}}"
    }
   ]
  },
  {
   "title": "Pkts In",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(f5_clientside_pktsIn{instance=~\"$device\", virtualServers=~\"$vs\"}[5m])",
     "legendFormat": "{{virtualServers}}"
    }
   ]
  },
  {
   "title": "Pkts Out",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(f5_clientside_pktsOut{instance=~\"$device\", virtualServers=~\"$vs\"}[5m])",
     "legendFormat": "{{virtualServers}}"
    }
   ]
  },
  {
   "title": "Traffic In",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(f5_clientside_bitsIn{instance=~\"$device\", virtualServers=~\"$vs\"}[5m])",
     "legendFormat": "{{virtualServers}}"
    }
   ]
  },
  {
   "title": "Traffic Out",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(f5_clientside_bitsOut{instance=~\"$device\", virtualServers=~\"$vs\"}[5m])",
     "legendFormat": "{{virtualServers}}"
    }
   ]
  },
  {
   "title": "Connections to VS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(instance) (f5_clientside_curConns{instance=~\"$device\", virtualServers=~\"$vs\"})",
     "legendFormat": "Current"
    },
    {
     "expr": "sum by(instance) (rate(f5_clientside_evictedConns{instance=~\"$device\", virtualServers=~\"$vs\"}[5m]))",
     "legendFormat": "Evicted"
    }
   ]
  },
  {
   "title": "Requests rate by VS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(f5_totRequests{instance=~\"$device\", virtualServers=~\"$vs\"}[$__rate_interval])",
     "legendFormat": "{{virtualServers}}"
    }
   ]
  },
  {
   "title": "Requests rate by pool",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(f5_totRequests{instance=~\"$device\", pools=~\"$pool\", members=~\"\"}[$__rate_interval])",
     "legendFormat": "{{pools}}"
    }
   ]
  },
  { "title": "Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Traffic In",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(f5_serverside_bitsIn{instance=~\"$device\", members=~\"\"}[$__rate_interval])",
     "legendFormat": "{{pools}}"
    }
   ]
  },
  {
   "title": "Traffic Out",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(f5_serverside_bitsOut{instance=~\"$device\", pools=~\"$pool\", members=~\"\"}[$__rate_interval])",
     "legendFormat": "{{pools}}"
    }
   ]
  },
  {
   "title": "Pkts In",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(f5_serverside_pktsIn{instance=~\"$device\", pools=~\"$pool\", members=~\"\"}[$__rate_interval])",
     "legendFormat": "{{pools}}"
    }
   ]
  },
  {
   "title": "Pkts Out",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(f5_serverside_pktsOut{instance=~\"$device\", pools=~\"$pool\", members=~\"\"}[$__rate_interval])",
     "legendFormat": "{{pools}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by(pools) (rate(f5_serverside_curConns{instance=~\"$device\", pools=~\"$pool\"}[$__rate_interval]))",
     "legendFormat": "{{pools}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(pools) (f5_serverside_curConns{instance=~\"$device\", pools=~\"$pool\"})",
     "legendFormat": "{{pools}}"
    }
   ]
  },
  {
   "title": "Pool Member Current Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(f5_serverside_totConns{instance=~\"$device\", pools=~\"$pool\", members=~\"$member\"}[$__rate_interval])",
     "legendFormat": "{{members}}"
    }
   ]
  },
  {
   "title": "Traffic In",
   "type": "stat",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(f5_serverside_bitsIn{instance=~\"$device\", pools=~\"$pool\", members=~\"\"}[$__rate_interval])",
     "legendFormat": "{{pools}}"
    }
   ]
  },
  {
   "title": "Traffic Out",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(f5_serverside_bitsOut{instance=~\"$device\", pools=~\"$pool\", members=~\"\"}[5m])",
     "legendFormat": "{{pools}}"
    }
   ]
  },
  { "title": "TLS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "t/s" } },
   "targets": [
    {
     "expr": "f5_system_throughputPerformance_sslTps_average{instance=~\"$device\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "t/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_system_throughputPerformance_sslTps_current{instance=~\"$device\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Active client connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f5_system_connectionsPerformance_activeSslClientConnections_average{instance=~\"$device\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "New client connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f5_system_connectionsPerformance_newSslClientConnections_average{instance=~\"$device\"}",
     "legendFormat": " {{instance}}"
    }
   ]
  },
  {
   "title": "Active server connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f5_system_connectionsPerformance_activeSslServerConnections_average{instance=~\"$device\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "New server connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "f5_system_connectionsPerformance_newSslServerConnections_average{instance=~\"$device\"}",
     "legendFormat": " {{instance}}"
    }
   ]
  }
 ]
}