{
 "title": "TS Prometheus Dashboard for F5 BIG-IP",
 "description": "Dashboard for the F5 BIG-IP Telemetry Streaming with Prometheus",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "prometheus" },
   {
    "name": "device",
    "query": {
     "query": "label_values(f5_system_cpu, instance)"
    }
   },
   {
    "name": "virtualServers",
    "label": "Virtual Servers",
    "query": {
     "query": "label_values(f5_clientside_bitsIn{instance=\"$device\"}, virtualServers)"
    }
   },
   {
    "name": "Pools",
    "label": "pools",
    "query": {
     "query": "label_values(f5_serverside_bitsIn{instance=\"$device\"}, pools)"
    }
   },
   {
    "name": "httpProfile",
    "label": "HTTP Profile",
    "query": {
     "query": "label_values(f5_getReqs{instance=\"$device\"}, httpProfiles)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Application Health Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Profile 5xx Responses",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "f5_5xxResp{httpProfiles=\"$httpProfile\",instance=\"$device\"}",
     "target": "aliasByNode(summarize(nonNegativeDerivative(stats.gauges.f5telemetry.$Device.httpProfiles.*.5xxResp), '2min'), 5)"
    }
   ]
  },
  {
   "title": "HTTP Profile 4xx Responses",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "f5_4xxResp{httpProfiles=\"$httpProfile\",instance=\"$device\"}"
    }
   ]
  },
  {
   "title": "HTTP_3XX RESPONSE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_3xxResp{httpProfiles=\"$httpProfile\",instance=\"$device\"}"
    }
   ]
  },
  {
   "title": "HTTP_2XX RESPONSE",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_2xxResp{httpProfiles=\"$httpProfile\",instance=\"$device\"}"
    }
   ]
  },
  { "title": "Device System Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "BIG-IP Device CPU %",
   "type": "gauge",
   "description": "The internal system and tmm cpu usage",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_system_cpu{instance=\"$device\"}",
     "legendFormat": "system_cpu",
     "target": "aliasByNode(stats.gauges.f5telemetry.$Device.system.tmmCpu, 3, 5)"
    },
    {
     "expr": "f5_system_tmmCpu{instance=\"$device\"}",
     "legendFormat": "tmmCpu",
     "target": "aliasByNode(stats.gauges.f5telemetry.$Device.system.cpu, 3, 5)"
    }
   ]
  },
  {
   "title": "BIG-IP Device Memory %",
   "type": "gauge",
   "description": "The internal system and tmm memory usage",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "f5_system_memory{instance=\"$device\"}",
     "legendFormat": "system_memory"
    },
    {
     "expr": "f5_system_tmmMemory{instance=\"$device\"}",
     "legendFormat": "tmmMemory"
    }
   ]
  },
  {
   "title": "TTM Clientside Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(f5_system_tmmTraffic_clientSideTraffic_bitsIn{instance=\"$device\"}[5m])",
     "legendFormat": "{{$device}}",
     "target": "aliasByNode(derivative(keepLastValue(stats.gauges.f5telemetry.$Device.system.tmmTraffic.clientSideTraffic-bitsIn)), 3)"
    }
   ]
  },
  {
   "title": "TTM Clientside Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(f5_system_tmmTraffic_clientSideTraffic_bitsOut{instance=\"$device\"}[5m])",
     "legendFormat": "{{$device}}",
     "target": "aliasByNode(derivative(keepLastValue(stats.gauges.f5telemetry.$Device.system.tmmTraffic.clientSideTraffic-bitsOut)), 3)"
    }
   ]
  },
  {
   "title": "TTM Serverside Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "irate(f5_system_tmmTraffic_serverSideTraffic_bitsIn{instance=\"$device\"}[5m])",
     "legendFormat": "{{$device}}",
     "target": "aliasByNode(derivative(keepLastValue(stats.gauges.f5telemetry.$Device.system.tmmTraffic.serverSideTraffic-bitsIn)), 3)"
    }
   ]
  },
  {
   "title": "TTM Serverside Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "irate(f5_system_tmmTraffic_serverSideTraffic_bitsOut{instance=\"$device\"}[5m])",
     "legendFormat": "{{$device}}"
    }
   ]
  },
  {
   "title": "Mgmt Interface Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "rate(f5_counters_bitsIn{instance=\"$device\",networkInterfaces=\"mgmt\"}[5m])",
     "legendFormat": "{{networkInterfaces}}",
     "target": "aliasByNode(derivative(keepLastValue(stats.gauges.f5telemetry.$Device.system.networkInterfaces.mgmt.counters-bitsIn)), 3)"
    }
   ]
  },
  {
   "title": "Mgmt Interface Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "irate(f5_counters_bitsOut{instance=\"$device\",networkInterfaces=\"mgmt\"}[5m])",
     "legendFormat": "{{networkInterfaces}}",
     "target": "aliasByNode(derivative(keepLastValue(stats.gauges.f5telemetry.$Device.system.networkInterfaces.mgmt.counters-bitsOut)), 3)"
    }
   ]
  },
  {
   "title": "1.1 Interface Traffic In",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "irate(f5_counters_bitsIn{instance=\"$device\",networkInterfaces=\"1.1\"}[5m])",
     "legendFormat": "{{networkInterfaces}}",
     "target": "aliasByNode(derivative(keepLastValue(stats.gauges.f5telemetry.$Device.system.networkInterfaces.1-0.counters-bitsIn)), 3)"
    }
   ]
  },
  {
   "title": "1-1 Interface Traffic Out",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "decbits" }
   ],
   "targets": [
    {
     "expr": "irate(f5_counters_bitsOut{instance=\"$device\",networkInterfaces=\"1.1\"}[5m])",
     "legendFormat": "{{networkInterfaces}}",
     "target": "aliasByNode(derivative(keepLastValue(stats.gauges.f5telemetry.$Device.system.networkInterfaces.1-0.counters-bitsOut)), 3)"
    }
   ]
  },
  { "title": "Virtual Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Virtual Server Client Traffic In",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "f5_clientside_bitsIn{instance=\"$device\",virtualServers=~\"$virtualServers\"}",
     "legendFormat": "{{virtualServers}}",
     "target": "aliasByNode(derivative(keepLastValue(stats.gauges.f5telemetry.$Device.virtualServers.-$Tenant-$Application-$VirtualServer.clientside-bitsIn)), 5)"
    }
   ]
  },
  {
   "title": "Virtual Server Client Traffic Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "f5_clientside_bitsOut{instance=\"$device\",virtualServers=~\"$virtualServers\"}",
     "legendFormat": "{{virtualServers}}",
     "target": "aliasByNode(derivative(keepLastValue(stats.gauges.f5telemetry.$Device.virtualServers.-$Tenant-$Application-$VirtualServer.clientside-bitsOut)), 5)"
    }
   ]
  },
  {
   "title": "Virtual Server Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "f5_clientside_curConns{instance=\"$device\",virtualServers=~\"$virtualServers\"}",
     "legendFormat": "{{virtualServers}}",
     "target": "aliasByNode(nonNegativeDerivative(keepLastValue(stats.gauges.f5telemetry.$Device.virtualServers.-$Tenant-$Application-$VirtualServer.clientside-curConns)), 5)"
    }
   ]
  },
  { "title": "Pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Pool Traffic In",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "f5_serverside_bitsIn{instance=\"$device\",pools=~\"$Pools\"}",
     "legendFormat": "{{pools}}",
     "target": "aliasByNode(nonNegativeDerivative(keepLastValue(stats.gauges.f5telemetry.$Device.pools.-$Tenant-$Application-$Pool.serverside-bitsIn)), 5)"
    }
   ]
  },
  {
   "title": "Pool Traffic Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "f5_serverside_bitsOut{instance=\"$device\",pools=~\"$Pools\"}",
     "legendFormat": "{{pools}}",
     "target": "aliasByNode(nonNegativeDerivative(keepLastValue(stats.gauges.f5telemetry.$Device.pools.-$Tenant-$Application-$Pool.serverside-bitsOut)), 5)"
    }
   ]
  },
  {
   "title": "Pool Total Request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "f5_totRequests{instance=\"$device\",pools=~\"$Pools\"}",
     "legendFormat": "{{pools}}",
     "target": "aliasByNode(nonNegativeDerivative(keepLastValue(stats.gauges.f5telemetry.$Device.pools.-$Tenant-$Application-$Pool.serverside-curConns)), 5)"
    }
   ]
  },
  {
   "title": "Pool Member Traffic Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "f5_serverside_bitsOut{instance=\"$device\",pools=~\"$Pools\"}",
     "legendFormat": "{{pools}} {{members}}",
     "target": "aliasByNode(nonNegativeDerivative(keepLastValue(stats.gauges.f5telemetry.$Device.pools.-$Tenant-$Application-$Pool.members.-$Tenant-*.serverside-bitsOut)), 7)"
    }
   ]
  },
  {
   "title": "Pool Member Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "f5_serverside_curConns{instance=\"$device\",pools=~\"$Pools\"}",
     "legendFormat": "{{pools}} {{members}}",
     "target": "aliasByNode(nonNegativeDerivative(keepLastValue(stats.gauges.f5telemetry.$Device.pools.-$Tenant-$Application-$Pool.members.-$Tenant-*.serverside-curConns)), 7)"
    }
   ]
  },
  {
   "title": "Profiles",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Profile Details",
     "type": "graph",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "target": "aliasByNode(nonNegativeDerivative(keepLastValue(stats.gauges.f5telemetry.$Device.httpProfiles.-$Profile.*)), 6)"
      }
     ]
    },
    {
     "title": "ClientSSL Profile Details",
     "type": "graph",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "f5_protocolUses_sslv2{clientSslProfiles=\"/Common/clientssl\",instance=\"$device\"}",
       "legendFormat": "clientssl",
       "target": "aliasByNode(nonNegativeDerivative(keepLastValue(stats.gauges.f5telemetry.$Device.clientSslProfiles.-$Profile.*)), 6)"
      },
      {
       "expr": "f5_protocolUses_sslv2{clientSslProfiles=\"/Common/clientssl-insecure-compatible\",instance=\"$device\"}",
       "legendFormat": "clientssl-insecure-compatible"
      },
      {
       "expr": "f5_protocolUses_sslv2{clientSslProfiles=\"/Common/clientssl-secure\",instance=\"$device\"}",
       "legendFormat": "clientssl-secure"
      }
     ]
    },
    {
     "title": "ServerSSL Profile Details",
     "type": "graph",
     "gridPos": { "h": 16, "w": 24, "x": 0, "y": 83 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "f5_protocolUses_sslv2{instance=\"$device\",serverSslProfiles=\"/Common/serverssl\"}",
       "legendFormat": "serverssl",
       "target": "aliasByNode(nonNegativeDerivative(keepLastValue(stats.gauges.f5telemetry.$Device.serverSslProfiles.-$Profile.*)), 6)"
      },
      {
       "expr": "f5_protocolUses_sslv2{instance=\"$device\",serverSslProfiles=\"/Common/serverssl-insecure-compatible\"}",
       "legendFormat": "insecure-compatible"
      },
      {
       "expr": "f5_protocolUses_sslv2{instance=\"$device\",serverSslProfiles=\"/Common/apm-default-serverssl\"}",
       "legendFormat": "apm-default-serverssl"
      }
     ]
    }
   ]
  }
 ]
}