{
 "title": "HTTP",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "device",
    "label": "BIG-IP",
    "query": {
     "query": "label_values(f5_system_tmmCpu, instance)"
    }
   },
   {
    "name": "profile",
    "label": "Profile",
    "query": {
     "query": "label_values(f5_2xxResp, httpProfiles)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request version",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(f5_v9Reqs{instance=~\"$device\", httpProfiles=~\"$profile\"}[5m]))",
     "legendFormat": "HTTP/0.9"
    },
    {
     "expr": "sum by(instance) (rate(f5_v10Reqs{instance=~\"$device\", httpProfiles=~\"$profile\"}[5m]))",
     "legendFormat": "HTTP/1"
    },
    {
     "expr": "sum by(instance) (rate(f5_v11Reqs{instance=~\"$device\", httpProfiles=~\"$profile\"}[5m]))",
     "legendFormat": "HTTP/1.1"
    },
    {
     "expr": "sum by(instance) (rate(f5_v20Reqs{instance=~\"$device\", httpProfiles=~\"$profile\"}[5m]))",
     "legendFormat": "HTTP/2"
    },
    {
     "expr": "sum by(instance) (rate(f5_v30Reqs{instance=~\"$device\", httpProfiles=~\"$profile\"}[5m]))",
     "legendFormat": "HTTP/3"
    }
   ]
  },
  {
   "title": "Response version",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum by(instance) (rate(f5_v9Resp{instance=~\"$device\", httpProfiles=~\"$profile\"}[5m]))",
     "legendFormat": "HTTP/0.9"
    },
    {
     "expr": "sum by(instance) (rate(f5_v10Resp{instance=~\"$device\", httpProfiles=~\"$profile\"}[5m]))",
     "legendFormat": "HTTP/1"
    },
    {
     "expr": "sum by(instance) (rate(f5_v11Resp{instance=~\"$device\", httpProfiles=~\"$profile\"}[5m]))",
     "legendFormat": "HTTP/1.1"
    },
    {
     "expr": "sum by(instance) (rate(f5_v20Resp{instance=~\"$device\", httpProfiles=~\"$profile\"}[5m]))",
     "legendFormat": "HTTP/2"
    },
    {
     "expr": "sum by(instance) (rate(f5_v30Resp{instance=~\"$device\", httpProfiles=~\"$profile\"}[5m]))",
     "legendFormat": "HTTP/3"
    }
   ]
  },
  {
   "title": "Responde code",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(f5_2xxResp{instance=~\"$device\", httpProfiles=~\"$profile\"}[5m]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum by(instance) (rate(f5_3xxResp{instance=~\"$device\", httpProfiles=~\"$profile\"}[5m]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum by(instance) (rate(f5_4xxResp{instance=~\"$device\", httpProfiles=~\"$profile\"}[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum by(instance) (rate(f5_5xxResp{instance=~\"$device\", httpProfiles=~\"$profile\"}[5m]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Methods",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expression": "$A + $B", "type": "math" },
    {
     "expr": "sum(rate(f5_numberReqs{instance=~\"$device\", httpProfiles=~\"$profile\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  }
 ]
}