{
 "title": "Application Security",
 "description": "F5 BIG-IP Advanced WAF and NGINX App Protect dashboard",
 "tags": [
  "f5",
  "waf",
  "nginx",
  "bigip"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vs_name",
    "label": "Virtual Server",
    "query": "{\"find\": \"terms\", \"field\": \"vs_name.keyword\"}"
   },
   {
    "name": "violation",
    "label": "Violation",
    "query": "{\"find\": \"terms\", \"field\": \"violations.keyword\"}"
   },
   { "name": "source_ip", "label": "Source IP", "query": "*" },
   { "name": "support_id", "label": "Support ID", "query": "*" },
   {
    "name": "policy",
    "label": "Policy",
    "query": "{\"find\": \"terms\", \"field\": \"policy_name.keyword\"}"
   },
   {
    "name": "logsource",
    "label": "Log Source",
    "query": "{\"find\": \"terms\", \"field\": \"logsource.keyword\"}"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "vs_name:$vs_name AND logsource:$logsource AND policy_name:$policy AND support_id:$support_id AND ip_client:$source_ip AND violations:\"N/A\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "vs_name:$vs_name AND logsource:$logsource AND policy_name:$policy AND support_id:$support_id AND ip_client:$source_ip AND NOT violations:\"N/A\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Action",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "request_status.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "10s", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      {
       "hide": false,
       "id": "1",
       "type": "count"
      }
     ],
     "query": "vs_name:$vs_name AND logsource:$logsource AND policy_name:$policy AND support_id:$support_id AND ip_client:$source_ip AND vs_name:$vs_name",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Virtual Servers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Virtual Servers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "vs_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "vs_name:$vs_name AND logsource:$logsource AND policy_name:$policy AND support_id:$support_id",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Virtual Server Violation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "vs_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "vs_name:$vs_name AND logsource:$logsource AND policy_name:$policy AND support_id:$support_id AND ip_client:$source_ip AND NOT violation:\"N/A\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Virtual Servers",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "vs_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "vs_name:$vs_name AND logsource:$logsource AND policy_name:$policy AND support_id:$support_id AND ip_client:$source_ip AND NOT violation_rating:\"0\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Violations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "violation_rating.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "asc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "vs_name:$vs_name AND logsource:$logsource AND policy_name:$policy AND support_id:$support_id AND ip_client:$source_ip AND NOT violations:\"N/A\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 10, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "count" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "violations.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "20" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "vs_name:$vs_name AND logsource:$logsource AND policy_name:$policy AND support_id:$support_id AND ip_client:$source_ip AND NOT violations:\"N/A\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 28 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "violation_rating.keyword",
       "id": "3",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "geoip.longitude",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "geoip.latitude",
       "id": "5",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "vs_name:$vs_name AND logsource:$logsource AND policy_name:$policy AND support_id:$support_id AND ip_client:$source_ip AND NOT violations.keyword:\"N/A\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "violations.keyword",
       "id": "4",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "20" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "vs_name:$vs_name AND logsource:$logsource AND policy_name:$policy AND support_id:$support_id AND ip_client:$source_ip AND NOT violations:\"N/A\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Top x", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Top Talkers",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ip_client.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "vs_name:$vs_name AND logsource:$logsource AND policy_name:$policy AND support_id:$support_id AND ip_client:$source_ip AND vs_name:$vs_name",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Violator IPs",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ip_client.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "vs_name:$vs_name AND logsource:$logsource AND policy_name:$policy AND support_id:$support_id AND ip_client:$source_ip AND NOT violations:\"N/A\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Violator IPs",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ip_client.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      },
      {
       "field": "@timestamp",
       "id": "3",
       "settings": { "interval": "1m", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "vs_name:$vs_name AND logsource:$logsource AND policy_name:$policy AND support_id:$support_id AND ip_client:$source_ip AND NOT violations:\"N/A\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top URLs",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 74 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "uri.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "vs_name:$vs_name AND logsource:$logsource AND policy_name:$policy AND support_id:$support_id AND ip_client:$source_ip",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Bots", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 } },
  {
   "title": "Bot Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "vs_name:$vs_name AND logsource:$logsource AND policy_name:$policy AND support_id:$support_id AND ip_client:$source_ip AND bot_anomalies:\"N/A\"",
     "timeField": "@timestamp"
    },
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "10s" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "vs_name:$vs_name AND logsource:$logsource AND policy_name:$policy AND support_id:$support_id AND ip_client:$source_ip AND NOT bot_anomalies:\"N/A\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Bot Anomalies",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "bot_anomalies.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "vs_name:$vs_name AND logsource:$logsource AND policy_name:$policy AND support_id:$support_id AND ip_client:$source_ip AND NOT bot_anomalies:\"N/A\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Bot Categories",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 95 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "bot_category.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "vs_name:$vs_name AND logsource:$logsource AND policy_name:$policy AND support_id:$support_id AND ip_client:$source_ip AND NOT bot_category:\"N/A\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Bot Signatures",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 95 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "bot_signature_name.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "vs_name:$vs_name AND logsource:$logsource AND policy_name:$policy AND support_id:$support_id AND ip_client:$source_ip AND NOT bot_signature_name:\"N/A\"",
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 104 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "vs_name:$vs_name AND logsource:$logsource AND policy_name:$policy AND support_id:$support_id AND ip_client:$source_ip AND violations:$violation",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Events",
   "type": "table",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 109 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "100" }, "type": "logs" }
     ],
     "query": "vs_name:$vs_name AND logsource:$logsource AND policy_name:$policy AND support_id:$support_id AND ip_client:$source_ip AND violations:$violation",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}